// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/common/Banner.vue')['default']
    copy: typeof import('./src/components/layout/header/Header copy.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/Footer.vue')['default']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Menu: typeof import('./src/components/layout/menu/Menu.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/MenuList.vue')['default']
    PlayerAction: typeof import('./src/components/layout/footer/PlayerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/PlayerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/footer/PlayerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/PlayerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/footer/PlayerVolumeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/header/SearchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/header/SearchSuggest.vue')['default']
    Title: typeof import('./src/components/common/Title.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/UserInfo.vue')['default']
  }
}
