export interface TopSong {
  starred: boolean
  popularity: number
  starredNum: number
  playedNum: number
  dayPlays: number
  hearTime: number
  mp3Url: string
  rtUrls?: any
  audition: any
  ringtone: string
  disc: string
  no: number
  status: number
  crbt: any
  bMusic: any
  rtUrl: any
  alias: any[]
  artists: any[]
  copyFrom: string
  mMusic: any
  lMusic: any
  hMusic: any
  score: number
  copyrightId: number
  album: any
  commentThreadId: string
  fee: number
  mvid: number
  ftype: number
  rtype: number
  rurl: null
  position: number
  duration: number
  name: string
  id: number
  exclusive: boolean
  privilege: any
}
